using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AZORD_CANTINE.CONNECTBD.INTERPHACE
{
    class REQUETE
    {
        public static string LIMITE_ANNE_AJOUTER="SELECT (ISNULL(MAX(NIVEAU),0)+1) FROM NIVEAU";
        public  string NIVEAU = "SELECT NIVEAU FROM NIVEAU";
        public  string SECTION = "SELECT SECTION.ABREVIATION FROM SECTION";
        public string NIVEAU_COMBO = "SELECT NIVEAU.NIVEAU FROM NIVEAU INNER JOIN CLASSE ON CLASSE.NIVEAU=NIVEAU.ID";
        public string SECTION_COMBO = "SELECT SECTION.ABREVIATION FROM SECTION INNER JOIN CLASSE ON CLASSE.SECTION=SECTION.ID INNER JOIN NIVEAU ON NIVEAU.ID=CLASSE.NIVEAU WHERE NIVEAU.NIVEAU=";
        public string DESIGNATION_COMBO = "SELECT DESIGNATION FROM SALLE_DE_CLASSE where NIVEAU=";
        public string NOMBREELEVESALLE = "";
    }
}
